config/routes.rb
Mijook::Application.routes.draw do
  post "pause" => "songs#pause"
  post "stop" => "songs#stop"
  post "play" => "songs#play"
  post "empty" => "songs#empty"
  post "next" => "songs#next"
  post "prev" => "songs#prev"
  post "vol_up" => "songs#vol_up"
  post "vol_down" => "songs#vol_down"
  resources :songs

  root :to => 'songs#index'

end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/controllers/application_controller.rb
require 'vlc_client'

class ApplicationController < ActionController::Base
  protect_from_forgery
  VLC = VlcClient.new "localhost", "8765"
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  def pause
    respond_to do |format|
      VLC.pause
      format.html { redirect_to songs_path }
    end
  end

  def stop
    respond_to do |format|
      VLC.stop
      format.html { redirect_to songs_path }
    end
  end

  def play
    respond_to do |format|
      VLC.play
      format.html { redirect_to songs_path }
    end
  end

  def empty
    respond_to do |format|
      VLC.empty
      format.html { redirect_to songs_path }
    end
  end

  def prev
    respond_to do |format|
      VLC.prev
      format.html { redirect_to songs_path }
    end
  end

  def next
    respond_to do |format|
      VLC.next
      format.html { redirect_to songs_path }
    end
  end

  def vol_up
    respond_to do |format|
      VLC.vol_up
      format.html { redirect_to songs_path }
    end
  end

  def vol_down
    respond_to do |format|
      VLC.vol_down
      format.html { redirect_to songs_path }
    end
  end
  
  
  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      @song.queued = false
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
    enqueue_unqueued_songs
  end

  def enqueue_unqueued_songs
    songs_in_queue = Song.where(:queued => false)
    songs_in_queue.each do |s|
      VLC.enqueue s.url
      @song.queued = true
      @song.save
    end
    VLC.play
  end
  
  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mijook</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.url %></td>
    <td><%= link_to 'Show', song %></td>
    <td><%= link_to 'Edit', edit_song_path(song) %></td>
    <td><%= link_to 'Destroy', song, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_song_path %>
<br />
<%= link_to 'Pause', pause_path, :method => :post %>
<br />
<%= link_to 'Stop', stop_path, :method => :post %>
<br />
<%= link_to 'Play', play_path, :method => :post %>
<br />
<%= link_to 'Clear', empty_path, :method => :post %>
<br />
<%= link_to 'Song++', next_path, :method => :post %>
<br />
<%= link_to 'Song--', prev_path, :method => :post %>
<br />
<%= link_to 'Vol--', vol_down_path, :method => :post %>
<br />
<%= link_to 'Vol++', vol_up_path, :method => :post %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @song.url %>
</p>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>